estructura/urls.py
from django.urls import path

from estructura import views


urlpatterns = (
    path("estructura/Recinto/", views.RecintoListView.as_view(), name="estructura_Recinto_list"),
    path("estructura/Recinto/create/", views.RecintoCreateView.as_view(), name="estructura_Recinto_create"),
    path("estructura/Recinto/detail/<int:pk>/", views.RecintoDetailView.as_view(), name="estructura_Recinto_detail"),
    path("estructura/Recinto/update/<int:pk>/", views.RecintoUpdateView.as_view(), name="estructura_Recinto_update"),
    path("estructura/Canton/", views.CantonListView.as_view(), name="estructura_Canton_list"),
    path("estructura/Canton/create/", views.CantonCreateView.as_view(), name="estructura_Canton_create"),
    path("estructura/Canton/detail/<int:pk>/", views.CantonDetailView.as_view(), name="estructura_Canton_detail"),
    path("estructura/Canton/update/<int:pk>/", views.CantonUpdateView.as_view(), name="estructura_Canton_update"),
    path("estructura/Zona/", views.ZonaListView.as_view(), name="estructura_Zona_list"),
    path("estructura/Zona/create/", views.ZonaCreateView.as_view(), name="estructura_Zona_create"),
    path("estructura/Zona/detail/<int:pk>/", views.ZonaDetailView.as_view(), name="estructura_Zona_detail"),
    path("estructura/Zona/update/<int:pk>/", views.ZonaUpdateView.as_view(), name="estructura_Zona_update"),
    path("estructura/Parroquia/", views.ParroquiaListView.as_view(), name="estructura_Parroquia_list"),
    path("estructura/Parroquia/create/", views.ParroquiaCreateView.as_view(), name="estructura_Parroquia_create"),
    path(
        "estructura/Parroquia/detail/<int:pk>/",
        views.ParroquiaDetailView.as_view(),
        name="estructura_Parroquia_detail"
    ),
    path(
        "estructura/Parroquia/update/<int:pk>/",
        views.ParroquiaUpdateView.as_view(),
        name="estructura_Parroquia_update"
    ),
    path("estructura/Provincia/", views.ProvinciaListView.as_view(), name="estructura_Provincia_list"),
    path("estructura/Provincia/create/", views.ProvinciaCreateView.as_view(), name="estructura_Provincia_create"),
    path(
        "estructura/Provincia/detail/<int:pk>/",
        views.ProvinciaDetailView.as_view(),
        name="estructura_Provincia_detail"
    ),
    path(
        "estructura/Provincia/update/<int:pk>/",
        views.ProvinciaUpdateView.as_view(),
        name="estructura_Provincia_update"
    ),
    path('gparroquia-autocomplete/', views.GParroquiaAutocomplete.as_view(), name='gparroquia-autocomplete', ),
    path('gzona-autocomplete/', views.GZonaAutocomplete.as_view(), name='gzona-autocomplete', ),
    path('gcanton-autocomplete/', views.GCantonAutocomplete.as_view(), name='gcanton-autocomplete', ),
    path('gprovincia-autocomplete/', views.GProvinciaAutocomplete.as_view(), name='gprovincia-autocomplete', ),
)

impugnaciones/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('estructura/', include('estructura.urls')),
    path('comparacion/', include('comparacion.urls')),
    path('tmp/', include('tmp.urls')),
    path('admin/', admin.site.urls),
    path('select2/', include("django_select2.urls")),
    path('', include("autenticacion.urls")),
    path('logout/', LogoutView.as_view(), name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

estructura/models.py
from django.db import models
from django.urls import reverse


class Provincia(models.Model):
    # Fields
    codprovincia = models.IntegerField(primary_key=True)
    nomprovincia = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'Provincia'
        verbose_name_plural = 'Provincias'

    def __str__(self):
        return str(self.nomprovincia)

    def get_absolute_url(self):
        return reverse("estructura_Provincia_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("estructura_Provincia_update", args=(self.pk,))


class Circunscripcion(models.Model):
    # Relationships
    provincia = models.ForeignKey("estructura.Provincia", on_delete=models.CASCADE)

    # Fields
    codcircunscripcion = models.IntegerField()
    nomcircunscripcion = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'Circunscripción'
        verbose_name_plural = 'Circunscripciones'

    def __str__(self):
        return str(self.nomcircunscripcion)

    def get_provincia(self):
        return str(self.provincia.nomprovincia)

    get_provincia.admin_order_field = 'provincia'


class Canton(models.Model):
    # Relationships
    provincia = models.ForeignKey("estructura.Provincia", on_delete=models.CASCADE)
    circunscripcion = models.ForeignKey("estructura.Circunscripcion", on_delete=models.CASCADE, null=True)

    # Fields
    codcanton = models.IntegerField(primary_key=True)
    nomcanton = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'Cantón'
        verbose_name_plural = 'Cantones'

    def __str__(self):
        return str(self.nomcanton)

    def get_provincia(self):
        return str(self.provincia.nomprovincia)

    get_provincia.admin_order_field = 'provincia'

    def get_absolute_url(self):
        return reverse("estructura_Canton_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("estructura_Canton_update", args=(self.pk,))


class Parroquia(models.Model):
    # Relationships
    canton = models.ForeignKey("estructura.Canton", on_delete=models.CASCADE)
    circunscripcion = models.ForeignKey("estructura.Circunscripcion", on_delete=models.CASCADE, null=True)

    # Fields
    codparroquia = models.IntegerField(primary_key=True)
    nomparroquia = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'Parroquia'
        verbose_name_plural = 'Parroquias'

    def __str__(self):
        return str(self.nomparroquia)

    def get_absolute_url(self):
        return reverse("estructura_Parroquia_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("estructura_Parroquia_update", args=(self.pk,))


class Zona(models.Model):
    # Relationships
    parroquia = models.ForeignKey("estructura.Parroquia", on_delete=models.CASCADE)
    circunscripcion = models.ForeignKey("estructura.Circunscripcion", on_delete=models.CASCADE, null=True)

    # Fields
    codzona = models.IntegerField()
    nomzona = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'Zona'
        verbose_name_plural = 'Zonas'

    def __str__(self):
        return str(self.codzona)

    def get_absolute_url(self):
        return reverse("estructura_Zona_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("estructura_Zona_update", args=(self.pk,))


class Recinto(models.Model):
    # Relationships
    parroquia = models.ForeignKey("estructura.Parroquia", on_delete=models.CASCADE)
    zona = models.ForeignKey("estructura.Zona", on_delete=models.CASCADE, null=True)

    # Fields
    codrecinto = models.IntegerField(primary_key=True)
    nomrecinto = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'Recinto'
        verbose_name_plural = 'Recintos'

    def __str__(self):
        return str(self.nomrecinto)

    def get_absolute_url(self):
        return reverse("estructura_Recinto_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("estructura_Recinto_update", args=(self.pk,))


class JRV(models.Model):
    # Relationships
    provincia = models.ForeignKey("estructura.Provincia", on_delete=models.CASCADE)
    circunscripcion = models.ForeignKey("estructura.Circunscripcion", on_delete=models.CASCADE, null=True)
    canton = models.ForeignKey("estructura.Canton", on_delete=models.CASCADE)
    parroquia = models.ForeignKey("estructura.Parroquia", on_delete=models.CASCADE)
    zona = models.ForeignKey("estructura.Zona", on_delete=models.CASCADE, null=True)
    recinto = models.ForeignKey("estructura.Recinto", on_delete=models.CASCADE)

    # Fields
    unes_cne_alert = models.BooleanField(default=False)
    suffragettes_votes_alert = models.BooleanField(default=False)
    max_total_votes_alert = models.BooleanField(default=False)
    suffragettes_alert = models.BooleanField(default=False)
    suffragettes_first_alert = models.BooleanField(default=False)
    null_votes_alert = models.BooleanField(default=False)
    blank_votes_alert = models.BooleanField(default=False)
    arauz_votes_alert = models.BooleanField(default=False)

    # Fields
    cod = models.CharField(max_length=30, primary_key=True)
    codcne = models.IntegerField(null=True)
    numero = models.IntegerField()
    genero = models.CharField(max_length=1)
    num_electores = models.IntegerField()
    quitaron = models.IntegerField(null=True)
    pusieron = models.IntegerField(null=True)
    appsufragantes = models.IntegerField(null=True)
    appblancos = models.IntegerField(null=True)
    appnulos = models.IntegerField(null=True)
    app_arauz = models.IntegerField(null=True)
    app_lasso = models.IntegerField(null=True)
    cnesufragantes = models.IntegerField(null=True)
    cneblancos = models.IntegerField(null=True)
    cnenulos = models.IntegerField(null=True)
    cne_arauz = models.IntegerField(null=True)
    cne_lasso = models.IntegerField(null=True)
    old_cne_sufragantes = models.IntegerField(null=True)
    old_cne_blancos = models.IntegerField(null=True)
    old_cne_nulos = models.IntegerField(null=True)
    old_cne_arauz = models.IntegerField(null=True)
    old_cne_lasso = models.IntegerField(null=True)
    difference_arauz = models.IntegerField(null=True)
    difference_lasso = models.IntegerField(null=True)
    para_validar = models.BooleanField(default=False)
    difnum1 = models.BooleanField(default=False)
    otro1 = models.CharField(max_length=30, null=True)
    no_procede = models.BooleanField(default=False)
    para_reclamar = models.BooleanField(default=False)
    incidencia = models.BooleanField(default=False)
    fecha_incidencia = models.DateTimeField(null=True)
    incidencia_grave = models.BooleanField(default=False)
    incidencia_resuelta = models.BooleanField(null=True)
    observaciones = models.TextField()
    telefonos = models.TextField()
    acta_delegados = models.CharField(max_length=255, null=True)
    acta_cne = models.CharField(max_length=255, null=True)
    acta_cnerecuento = models.CharField(max_length=255, null=True)
    noactapre = models.IntegerField(null=True)
    is_active = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'JRV'
        verbose_name_plural = 'JRVs'

    def __str__(self):
        return str(self.pk)

    def get_absolute_url(self):
        return reverse("estructura_JRV_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("estructura_JRV_update", args=(self.pk,))


class dignidad(models.Model):
    # Fields
    coddignidad = models.IntegerField(primary_key=True)
    nomdignidad = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'Dignidad'
        verbose_name_plural = 'Dignidades'

    def __str__(self):
        return str(self.nomdignidad)

    def get_absolute_url(self):
        return reverse("estructura_dignidad_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("estructura_dignidad_update", args=(self.pk,))


class partido(models.Model):
    # Fields
    codpartido = models.IntegerField()
    nompartido = models.CharField(max_length=255)

    provincia = models.ForeignKey("estructura.Provincia", on_delete=models.CASCADE)
    dignidad = models.ForeignKey("estructura.dignidad", on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Partido'
        verbose_name_plural = 'Partidos'

    def __str__(self):
        return str(self.nompartido)

    def get_absolute_url(self):
        return reverse("estructura_partido_detail", args=(self.pk,))

    def get_update_url(self):
        return reverse("estructura_partido_update", args=(self.pk,))

templates/incidencias/edit_jrv_incidencia.html
{% extends 'layouts/base2.html' %}
{% load static %}
{% load pagination_tags %}

{% block title %} Consulta- Presidencia y Vicepresidencia {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

    <div class="modal-content" id="filetypeModal">

<div class="modal-header">
    <h3 class="modal-title">Detalles de JRV</h3>
    <button type="button" id="closeModal" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

        {% block content %}
            <div class="modal-body">

                <!DOCTYPE html>
                <html lang="es">
                <head>
                    <meta charset="utf-8">
                    <meta http-equiv="X-UA-Compatible" content="IE=edge">
                    <meta name="viewport" content="width=device-width, initial-scale=1">
                    <title>Detalle JRV</title>
                    <!-- Bootstrap -->
                </head>
                <body>

                <section>
                    <div class="container">
                        <div class="row">
                            <div class="col-12 text-center">
                                <table class="table table-striped" width="100%" >
                                    <tbody>
                                    <tr>
                                        <td><H5>Provincia</H5></td>
                                        <td>{{jrvactual.provincia}}</td>
                                        <td><H5>Canton</H5></td>
                                        <td>{{jrvactual.canton}} &nbsp;</td>
                                    </tr>
                                    <tr>
                                        <td><h5>Parroquia</h5></td>
                                        <td>{{jrvactual.parroquia}}</td>
                                        <td><h5>Zona</h5></td>
                                        <td>{{jrvactual.zona}}</td>
                                    </tr>
                                    <tr>
                                        <td><h5>Recinto</h5></td>
                                        <td>{{jrvactual.recinto}} </td>
                                        <td><h5>Jrv</h5></td>
                                        <td>{{jrvactual.numero}}{{jrvactual.genero}}</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <hr>

                    </div>
                </section>
                <hr>

                </body>
                </html>




                <section>




                    <style>

                        .vertical-center {
                            margin: 0;
                            position: absolute;
                            top: 50%;
                            -ms-transform: translateY(-50%);
                            transform: translateY(-50%);
                        }
                    </style>

                    <hr>

                    <form id="getAPI" method="post">
                        {% csrf_token %}

                        <div class="form-group">
                            <div class="container">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="Observaciones">Observaciones</label>
                                            <textarea class="form-control" rows="7" cols="40" name="Observaciones" >{{jrvactual.observaciones}}</textarea>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <div class="container vertical-center">

                                                <center><label>
                                                    <input type="checkbox" class="form-control" name="resuelta" value="Se resolvio" {% if resuelta == "si" %}checked="True"{% endif %} />Se resolvio</label></center>

                                                <center><label>
                                                    <input type="checkbox" class="form-control" name="grave" value="Incidencia Grave" {% if grave == "si" %}checked="True"{% endif %} />Incidencia Grave</label></center>
                                            </div>
                                        </div>
                                    </div>
                                    <input id="jrvactual" name="jrvactual" type="hidden" value={{jrvactual.pk}}>
                                    <div class="col-md-2">
                                        <input type="submit" class="btn btn-primary vertical-center " name="filtrar"  value="Guardar cambios">
                                    </div>

                                </div>

                            <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="Telefonos">Telefonos </label>
                                            <textarea class="form-control" rows="40 " cols="40" name="Telefonos" disabled>{{jrvactual.telefonos}}</textarea>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>



                    </form>

                    <script>
                        $("#getAPI").submit(function(event) {
                            event.preventDefault();
                            event.preventDefault();
                            event.preventDefault();
                        });
                        $.ajax({
                            url: '/comparacion/updated/',  // your url endpoint
                            type: 'POST',

                            data: $('#getAPI').serialize(),  // gather form data
                            success: function(data) {
                                console.log(data);
                                $("#filetypeModal").modal("toggle");  // Use toggle to close modal
                            }
                            // end success callback
                        });
                        $("#closeModal").click(event =>{
                            alert('Success');// end ajax call
                            // prevent default submission
                            event.preventDefault();
                        });
                    </script>

                </section>


            </div>
            </div>
        {% endblock content %}

templates/incidencias/incidencias.html
{% extends 'layouts/base2.html' %}
{% load static %}
{% load pagination_tags %}

{% block title %}Incidencias{% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
    <style type="text/css">
        table {
            width: 100%
        }
    </style>
{% endblock stylesheets %}

{% block content %}


<div class="pcoded-content">
        <!-- [ breadcrumb ] start -->

    {% if mensaje %}
        <script>
            alert('{{ mensaje }}');
        </script>
    {% endif %}
                <div class="row align-items-center">
                    <div class="col-md-6">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Incidencias</h5>
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html"><i class="feather icon-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="#!">Incidencias</a></li>
                            <li class="breadcrumb-item"><a href="javascript:">Incidencias</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <h5 class="m-b-10">Items en consulta:</h5> <h5>{{valores.vcount }}</h5>
                    </div>
                </div>

        <!-- [ breadcrumb ] end -->
        <div class="card card-body">


            <style>
                .name { font-weight: bold; }
                .subtext { font-size: smaller; }
            </style>


        <form method="post">
            {% csrf_token %}

            <div class="row">
                <div class="col-md-3">
                <center><h3>{{ valores.vprovincia }}</h3></center>
                </div>

                <div class="col-md-3">
                    <select class="mb-3 form-control" name="canton" id="canton">
                        <option value="*" selected >Todos los Cantones</option>
                        {% for canton in canton_list %}
                            <option value="{{canton.pk}}" >{{canton}}</option>
                        {% endfor %}
                    </select>
                </div>


                <div class="col-md-3">
                    <input type="submit" class="btn btn-primary" name="filtrar"  value="Buscar">
                </div>
             <script>
                document.getElementById('canton').value = {{valores.vcanton}};
            </script>
            </div>

            <div class="row">
                    <!-- [ stiped-table ] start -->
                    {% autopaginate jrv_list 20 %}
                    <table id="books-table" class="table-striped tall-row">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th >Fecha</th>
                            <th >Recinto</th>
                            <th>JRV</th>
                            <th>Observaciones</th>
                            <th>Ver JRV</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for jrv in jrv_list %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ jrv.fecha_incidencia }}</td>
                                <td >
                                <span class="name">{{ jrv.canton }} |{{ jrv.parroquia }} | Zona {{ jrv.zona }}</span>  <br/>
                                    <span class="subtext">{{ jrv.recinto }}</span></td>

                                <td>{{ jrv.numero }}{{ jrv.genero }}</td>
                                <td style="max-width: 200px; word-wrap: break-word; " >{{ jrv.observaciones }}</td>
                                <td>
                                    <!-- Botones para ver Modal popup -->
                                    <button type="button" class="btn btn-sm btn-primary" onclick="window.location.href='/comparacion/editar_incidencia/{{ jrv.pk }}'">
                                        <span class="fa fa-eye"></span>
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>

                    </table>
                    {% paginate  using "includes/pagination.html" %}
                    <!-- [ stiped-table ] end -->
                </div>
        </form>

        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}
{% block extrascripts %}{% endblock extrascripts %}